name: Auto Update PMC Stats

on:
  schedule:
    # Chạy mỗi 2 giờ một lần (Bạn có thể sửa số 2 thành số khác)
    # Lưu ý: Giờ hệ thống là giờ UTC (chậm hơn VN 7 tiếng)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Cho phép bấm nút chạy thủ công để test

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (Lấy code về)
      uses: actions/checkout@v2

    - name: Set up Python (Cài Python)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Chrome (Cài trình duyệt Chrome)
      uses: browser-actions/setup-chrome@latest

    - name: Install dependencies (Cài thư viện từ requirements.txt)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script (Chạy file code)
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: python get_all_stats.py
